### PR TITLE
Allow unsorted ts

### PR DESCRIPTION
**Pull request by pconesa**

### CODE REVIEW

**Review by azazellochg — CHANGES_REQUESTED** [review]
why this plugin is changed instead of https://github.com/scipion-em/scipion-em-tomo/blob/devel/tomo/objects.py#L297 ?
orderBy index is not used anywhere in scipion, because we order by id by default

**Comment by pconesa** [comment]
I'm changing that code too, but you are not using that method

**Comment by azazellochg** [comment]
the indexes are already sorted so I dont see the point of changing all plugins for this.

**Comment by pconesa** [comment]
I don0t think you re considering this case:
image

**Comment by azazellochg** [comment]
Thanks! I will test it out myself before merging it :)

**Comment by pconesa** [comment]
Sure, I might prepare a dataset with a non sorted TS.

**Review by azazellochg — APPROVED** [review]

**Pull request merged**
