### PR TITLE
Jj remove decorator

### PR DESCRIPTION
**Pull request by JorMaister**

### CODE REVIEW

**Comment by azazellochg** [comment]
```
00011:     File "/public/EM/Scipion/scipion-dev/scipion-em-plugins/scipion-em-aretomo/aretomo/protocols/protocol_aretomo.py", line 543, in createOutputTs
00012:       newTomogram.setCtfCorrected(ts.ctfCorrected())
00013:   AttributeError: 'Tomogram' object has no attribute 'setCtfCorrected'
00014:   Protocol failed: 'Tomogram' object has no attribute 'setCtfCorrected'
```

**Comment by azazellochg** [comment]
Aah, I see. Should we bump tomo version in requirements.txt here then?

**Comment by JorMaister** [comment]
Yes, let me do it

**Review by azazellochg — APPROVED** [review]

**Comment by azazellochg** [comment]
It would be good in the future to split the steps code into smaller methods, it is indeed difficult to read like sonarcloud says

**Comment by JorMaister** [comment]
Agreed :D

**Pull request merged**
