### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by JorMaister**
* Goes with https://github.com/scipion-em/scipion-em-tomo/pull/470
* The tests now use the Test Centralization Layer update and expansion and the used dataset expanded definition.
* Tests passing

### CODE REVIEW

**Comment by azazellochg** [comment]
Hi! I assume you want to merge to devel not master?

**Comment by JorMaister** [comment]
Hi, @azazellochg,

As it's a test update, it may remain in devel until more changes are sent to devel before making a release.

**Comment by azazellochg** [comment]
I'm confused, this PR targets the master, which contradicts with what you are saying

**Comment by JorMaister** [comment]
My fault, @azazellochg! I didn't notice that. I'll change it now. 

Many thanks

**Review by azazellochg — CHANGES_REQUESTED** [review]
All tests seem to fail with 
```
File "/public/EM/Scipion/scipion-dev/scipion-em-plugins/scipion-em-tomo/tomo/tests/test_base_centralized_layer.py", line 285, in checkTomoAcquisition
self.assertAlmostEqual(testAcq.getTiltAxisAngle(), currentAcq.getTiltAxisAngle(), delta=0.01)
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 966, in assertAlmostEqual
raise self.failureException(msg)
AssertionError: 85.3 != 85.068 within 0.01 delta (0.23199999999999932 difference)
```

**Comment by JorMaister** [comment]
Hi, @azazellochg, 
They're passing for me. Could you confirm If you are in the latest state of scipion-em-tomo (devel)?

**Comment by azazellochg** [comment]
Hi, yes I can confirm tomo in devel. I'm using:
ARETOMO_HOME = /public/EM/Scipion/scipion-dev/software/em/aretomo2-1.0.0
ARETOMO_CUDA_LIB = /public/EM/CUDA/cuda-11.8/lib64
ARETOMO_BIN = AreTomo2_1.0.0_Cuda118

**Comment by JorMaister** [comment]
The error when checking the dose was adjusted correctly because I found we had two slightly different values in the dataset definition depending on the importing way (tlt file or not). I found it and fix it, but it seems not to be reflected in your code... So I guess there may be something we don't have in the same code state. I assume you are in my branch in aretomo, the last state, and also in devel in scipion-em-tomo, the last state. And I don't see any uncommitted changes in any of these plugins. "At the risk of being overly pushy, can you confirm those code states again?

**Comment by JorMaister** [comment]
Test passing after having moved to devel in aretomo... Does it happen to you, @azazellochg ?

**Comment by azazellochg** [comment]
Hi, I think your guess is correct. It may be the binary or the GPU that gives different results. I get the same error in devel branch. Maybe we can relax the tolerance a bit?

**Review by azazellochg — APPROVED** [review]

**Pull request merged**
